-- ============================================================================
-- CYBER SHIELD - SUPABASE SCHEMA & RLS POLICIES
-- ============================================================================
-- Run this in the Supabase SQL Editor (Dashboard -> SQL -> New query).
-- It creates the tables and row-level-security policies used by the website.
-- ============================================================================

-- Realtime must be enabled for these tables for live history sync:
--   Dashboard -> Database -> Replication -> enable "Realtime" on `checks`.

-- ----------------------------------------------------------------------------
-- 1. PROFILES  (username -> email mapping for username-based login)
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  username   text not null unique,
  email      text not null,
  created_at timestamptz not null default now()
);

-- RLS: any authenticated user can read the profile mapping
-- (needed so login can resolve a username to an email).
-- Users can only create/update their own profile.
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (auth.uid() is not null);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create a profile row on signup from the username stored in
-- the user's metadata (set via signUp options.data.username).
-- This works even when email confirmation is enabled (no client session yet).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Backfill for users created before this trigger existed:
--   insert into public.profiles (id, username, email)
--   select id, split_part(email, '@', 1), email from auth.users
--   on conflict (id) do nothing;

-- ----------------------------------------------------------------------------
-- 2. CHECKS  (user scan history)
-- ----------------------------------------------------------------------------
create table if not exists public.checks (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users (id) on delete cascade,
  input_snippet text not null,
  verdict       text not null default 'safe',            -- safe | caution | danger
  reasons       jsonb not null default '[]'::jsonb,      -- array of reason keys
  language      text not null default 'en',              -- en | hi | te
  checked_for   text not null default 'family',          -- myself | family | community
  raw_type      text not null default 'link',            -- link | msg | qr
  created_at    timestamptz not null default now()
);

-- RLS: users can only read/write their own checks
alter table public.checks enable row level security;

drop policy if exists "checks_select_own" on public.checks;
create policy "checks_select_own"
  on public.checks for select
  using (auth.uid() = user_id);

drop policy if exists "checks_insert_own" on public.checks;
create policy "checks_insert_own"
  on public.checks for insert
  with check (auth.uid() = user_id);

drop policy if exists "checks_delete_own" on public.checks;
create policy "checks_delete_own"
  on public.checks for delete
  using (auth.uid() = user_id);

-- Gimme a helpful index for querying a user's history
create index if not exists checks_user_created_idx
  on public.checks (user_id, created_at desc);

-- ----------------------------------------------------------------------------
-- 3. REPORTS  (community scam database)
-- ----------------------------------------------------------------------------
create table if not exists public.reports (
  id               bigint generated by default as identity primary key,
  hashed           text not null unique,                -- dedup key for a scam snippet
  text             text not null,                       -- snippet of the reported scam
  verdict          text not null default 'danger',      -- danger | caution
  confirm_count    integer not null default 1,
  reported_by      uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),
  last_reported_at timestamptz
);

-- RLS: any authenticated user can read reports; only signed-in users can insert;
-- users can only update/delete their <own> contributions.
alter table public.reports enable row level security;

drop policy if exists "reports_select_all" on public.reports;
create policy "reports_select_all"
  on public.reports for select
  using (auth.uid() is not null);

drop policy if exists "reports_insert_auth" on public.reports;
create policy "reports_insert_auth"
  on public.reports for insert
  with check (auth.uid() = reported_by);

drop policy if exists "reports_update_own" on public.reports;
create policy "reports_update_own"
  on public.reports for update
  using (auth.uid() = reported_by);

drop policy if exists "reports_delete_own" on public.reports;
create policy "reports_delete_own"
  on public.reports for delete
  using (auth.uid() = reported_by);

-- ----------------------------------------------------------------------------
-- 4. SENDER REPORTS (community trust signal)
-- Only Edge Functions with the service-role key can write counts. Authenticated
-- clients can read a sender's existing count to display a safety warning.
-- ----------------------------------------------------------------------------
create table if not exists public.sender_reports (
  sender_value     text primary key,
  report_count     integer not null default 1 check (report_count > 0),
  last_reported_at timestamptz not null default now()
);

alter table public.sender_reports enable row level security;

drop policy if exists "sender_reports_read_authenticated" on public.sender_reports;
create policy "sender_reports_read_authenticated"
  on public.sender_reports for select
  using (auth.uid() is not null);

-- No insert/update/delete policies: browser clients cannot change counts.
create or replace function public.increment_sender_report(p_sender_value text)
returns public.sender_reports
language plpgsql
security definer
set search_path = public
as $$
declare result public.sender_reports;
begin
  insert into public.sender_reports (sender_value, report_count, last_reported_at)
  values (lower(trim(p_sender_value)), 1, now())
  on conflict (sender_value) do update
    set report_count = public.sender_reports.report_count + 1,
        last_reported_at = now()
  returning * into result;
  return result;
end;
$$;

revoke all on function public.increment_sender_report(text) from public;
